[project]
name = "tron1-rl-mjlab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mjlab",
]

[tool.uv.sources]
mjlab = { path = "../../mjlab", editable = true }
